#!/usr/bin/python3

import sys
import argparse
import json

TSURUGI_HOME='/usr/lib/tsurugi'

def main():
    parser = argparse.ArgumentParser(description='tgha stub')
    if len(sys.argv) < 3:
        print("lack of args")
        exit()

    parser.add_argument('command',  type=str, help='monitor file')
    parser.add_argument('subcommand',  type=str, help='monitor file')
    parser.add_argument('--monitor',  type=str, required=True, help='monitor file')
    parser.add_argument('--conf',  type=str, required=False, help='conf file')
    parser.add_argument('--auth-token',  type=str, required=False, help='auth token')
    parser.add_argument('--mode',  type=str, required=False, help='mode')
    parser.add_argument('--replicate-from',  type=str, required=False, help='replicate from')
    parser.add_argument('--auto-fetch-wal',  action='store_true', required=False, help='auto fetch WAL')
    parser.add_argument('--from',  dest='from_host', type=str, required=False, help='from')
    parser.add_argument('--auto',  action='store_true', required=False, help='auto')
    parser.add_argument('--timeout',  type=int, default=1, required=False, help='timeout')
    args = parser.parse_args()

    command = args.command
    subcommand = args.subcommand
    monitor_file = args.monitor
    mode = args.mode
    replicateFrom = args.replicate_from  
    autoFetchWal = args.auto_fetch_wal
    from_host = args.from_host
    auto = args.auto

    cmd = " ".join(sys.argv)
    out_log(cmd)
    with open(f"{TSURUGI_HOME}/bin/mode.txt", mode='r') as fc:
        current_mode = fc.read()
        current_mode = current_mode.strip('\n')

    match command:
        case "mode":
            mode_command(subcommand, monitor_file, mode, replicateFrom, autoFetchWal, current_mode)
        case "database":
            database_command(subcommand, monitor_file, from_host, auto, current_mode)
        case _:
            out_log(f"unknwon command: {command}")

def mode_command(subcommand:str, monitor_file: str, mode:str, replicateFrom: str, autoFetchWal:bool, current_mode:str):
    #print(f"{subcommand}, replicateFrom:{replicateFrom} autoFetchWal:{autoFetchWal}")

    result_dict_list = []
    match subcommand:
        case "show":
            result_dict = {
                "mode": current_mode, 
                "master.replication_status": "ok",
                "standby.replication_status": "ok",
                "replica.replication_status": "ok",
                "replica.upstream": "dns:///current_upstream:50051",
            }
            for k, v in result_dict.items():
                item = {"key": k, "value": v}
                result_dict_list.append(item)
            out_monitor(monitor_file, result_dict_list)
        case "switch":
            out_log("switch")
            out_mode(mode)
            if current_mode == mode:
                result_dict = {}
                result_dict["kind"] = 'finish'
                result_dict["status"] = 'failure'
                result_dict["reason"] = '10'
                result_dict["cause"] = ''
                result_dict["message"] = 'error:status not changed'
                result_dict_list.append(result_dict)
            elif current_mode == 'standalone' and mode == 'master':
                result_dict = {}
                result_dict["kind"] = 'finish'
                result_dict["status"] = 'failure'
                result_dict["reason"] = '11'
                result_dict["cause"] = ''
                result_dict["message"] = 'error:enable to switch master from standalone'
                result_dict_list.append(result_dict)
            else:
                result_dict = {}
                result_dict["kind"] = 'finish'
                result_dict["status"] = 'success'
                result_dict_list.append(result_dict)
            out_monitor(monitor_file, result_dict_list)
        case _:
            print(f"unknwon subcommand: {subcommand}")

def database_command(subcommand:str, monitor_file: str, from_host: str, auto:bool, current_mode:str):
    #print(f"{subcommand}, from:{from_host} auto:{auto}")
    result_dict_list = []
    match subcommand:
        case "version":
            result_dict = {}
            result_dict["key"] = "version"
            result_dict["value"] = "ver_123"
            result_dict_list.append(result_dict)
            out_monitor(monitor_file, result_dict_list)
        case "apply":
            if current_mode == 'running':
                result_dict = {}
                result_dict["kind"] = 'finish'
                result_dict["status"] = 'failure'
                result_dict["reason"] = '01'
                result_dict["cause"] = ''
                result_dict["message"] = 'error:database now running'
                result_dict_list.append(result_dict)
                out_monitor(monitor_file, result_dict_list)
                exit()

            result_dict = {}
            result_dict["kind"] = 'finish'
            result_dict["status"] = 'success'
            result_dict_list.append(result_dict)
            out_monitor(monitor_file, result_dict_list)
        case _:
            print(f"unknwon subcommand: {subcommand}")


def out_monitor(monitor_file:str, result_dict_list):
    with open(f"{monitor_file}", mode='w') as fc:
        for result_dict in result_dict_list:
            json.dump(result_dict, fc)
            fc.write('\n')

def out_mode(mode:str):
    with open(f"{TSURUGI_HOME}/bin/mode.txt", mode='w') as fc:
        fc.write(mode)

def out_log(log:str):
    with open('/tmp/tght_w_history.log', mode='a') as fc:
        fc.write(f"{log}\n")


"""
 Execute main()
"""
if __name__ == "__main__":
    main()
