TSURUGI_HOME=##TSURUGI_HOME##
BELAYER_HOME=##BELAYER_INSTALL_DIR##
BELAYER_LOG_LEVEL=WARN
BELAYER_ACCESS_LOG_ENABLED=false
# settings to output authentication/authorization errr log
#BELAYER_AUTH_ERROR_LOG_LEVEL=WARN
# settings to output access log file 
#RUN_ARGS="--server.jetty.accesslog.filename=/var/log/belayer_access_yyyy_MM_dd.log --server.jetty.accesslog.file-date-format=yyyy_MM_dd --server.jetty.accesslog.format=EXTENDED_NCSA"
JAVA_OPTS="${JAVA_OPTS}" #add -Xms=512M -Xmx512M -XX:MaxMetaspaceSize=512M and others
