version: '3.3'

services:
  belayer-e2e:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    tty: true
    volumes:
      - ../:/app
      - ../../remotecli/bin:/opt/belayer/stub/bin
    working_dir: /app
    environment:
      BELAYER_CLI_PATH: "/opt/belayer/stub/bin"
      BELAYER_API_HOST: "http://belayer-server-stub:8000"
      BELAYER_ENDPOINT_URL: "http://belayer-server-stub:8000"
    networks:
      - external
networks:
  external:
    name: belayer-network
    external: true