name: Belayer-WebAPI-CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: [self-hosted, docker]
    permissions:
      checks: write
    timeout-minutes: 30
    container:
      image: ghcr.io/project-tsurugi/tsurugi-ci:ubuntu-22.04
      volumes:
        - ${{ vars.gradle_cache_dir }}:/root/.gradle
    defaults:
      run:
        shell: bash

    steps:
      - name: Setup_Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Assemble_WebAPI
        run: |
          cd webapi
          ./gradlew -i clean assemble

      - name: Check_WebAPI
        run: |
          cd webapi
          ./gradlew -i check

      - name: Verify
        uses: project-tsurugi/tsurugi-annotations-action@v1
        if: always()
        with:
          junit_input: |
            webapi/build/test-results/**/TEST-*.xml
          spotbugs_input: webapi/build/reports/spotbugs/main/*.xml
          checkstyle_input: webapi/build/reports/checkstyle/main.xml
